version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mattchar
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: merch_store
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mattchar -d merch_store"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    environment:
      DATABASE_URL: "postgres://mattchar:1234@postgres:5432/merch_store?sslmode=disable"
      JWT_SECRET: "your_jwt_secret"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
